language: android
jdk: oraclejdk8
sudo: false

if: type == pull_request OR (type == push AND branch =~ /^release\/.*$/)

env:
  global:
  - ANDROID_API_LEVEL=28
  - ANDROID_BUILD_TOOLS_VERSION=28.0.3

android:
  components:
  - tools
  - platform-tools
  - android-$ANDROID_API_LEVEL
  - build-tools-$ANDROID_BUILD_TOOLS_VERSION

licenses:
- android-sdk-preview-license-.+
- android-sdk-license-.+
- google-gdk-license-.+

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  - $HOME/.android/build-cache

before_install:
- yes | sdkmanager "platforms;android-28"

after_failure:
- cat $TRAVIS_BUILD_DIR/app/build/reports/lint-results.xml

stages:
- name: debugBuild
  if: branch != master
- name: releaseBuild
  if: branch = master

jobs:
  include:
  - stage: debugBuild
    script:
    - ./gradlew clean check -P"sygic.sdk.key"=$SYGIC_API_KEY
    - ./gradlew assembleDebug -P"sygic.sdk.key"=$SYGIC_API_KEY
  - stage: releaseBuild
    script:
    - ./gradlew clean check -P"sygic.sdk.key"=$SYGIC_API_KEY
    #todo UI tests!
    - ./gradlew assembleRelease -P"sygic.sdk.key"=$SYGIC_API_KEY #todo credentials?
    deploy:
      provider: script #todo provider: releases
      script: echo 'deploing job done' #todo real deploy ;)
      file: $TRAVIS_BUILD_DIR/app/samples/build/outputs/apk/release/app-samples-arm64-v8a-release.apk
      skip_cleanup: true
      on:
        tags: true
    after_deploy:
    - rm -rf $TRAVIS_BUILD_DIR/app/samples/build/outputs
