language: android
jdk: oraclejdk8
sudo: false

env:
  global:
  - ANDROID_API_LEVEL=28
  - ANDROID_BUILD_TOOLS_VERSION=28.0.3

android:
  components:
  - tools
  - platform-tools
  - android-$ANDROID_API_LEVEL
  - build-tools-$ANDROID_BUILD_TOOLS_VERSION

licenses:
- android-sdk-preview-license-.+
- android-sdk-license-.+
- google-gdk-license-.+

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

#before_install:
#- yes | sdkmanager --licenses

script:
- ./gradlew clean build check -P"sygic.sdk.key"=$SYGIC_API_KEY

after_failure:
- cat $TRAVIS_BUILD_DIR/app/build/reports/lint-results.xml