language: android

jdk:
  - oraclejdk8

sudo: false

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
  - ./gradlew clean build -P"sygic.sdk.key"=$SYGIC_API_KEY

android:
 components:
 - tools
 - platform-tools
 - android-28
 - build-tools-28.0.3

 licenses:
   - android-sdk-preview-license-.+
   - android-sdk-license-.+
   - google-gdk-license-.+

#before_install:
  #- yes | sdkmanager --licenses