language: android

jdk:
  - oraclejdk8

sudo: false

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
  - "./gradlew clean build"

android:
 components:
 - tools
 - platform-tools

licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+