language: android
jdk: oraclejdk8
sudo: false

env:
  global:
  - ANDROID_API_LEVEL=28
  - ANDROID_BUILD_TOOLS_VERSION=28.0.3

android:
  components:
  - tools
  - platform-tools
  - android-$ANDROID_API_LEVEL
  - build-tools-$ANDROID_BUILD_TOOLS_VERSION

licenses:
- android-sdk-preview-license-.+
- android-sdk-license-.+
- google-gdk-license-.+

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

before_install:
- yes | sdkmanager "platforms;android-28"

stages:
- name: debugBuild
#  if: branch =~ ^\d+\.\d+\.\d+$ todo
- name: releaseBuild
#  if: branch = master OR branch =~ ^\d+\.\d+\.\d+$ todo

jobs:
  include:
  - stage: debugBuild
    script:
    - ./gradlew clean test #todo ./gradlew check # UI tests?
    - ./gradlew assembleDebug -P"sygic.sdk.key"=$SYGIC_API_KEY
  - stage: releaseBuild
    script:
    - ./gradlew clean test #todo ./gradlew check # UI tests?
    - ./gradlew assembleRelease -P"sygic.sdk.key"=$SYGIC_API_KEY
    deploy:
      provider: script
      script: echo 'deploing job done' #todo
      file: $TRAVIS_BUILD_DIR/app/samples/build/outputs/apk/release/app-samples-arm64-v8a-release.apk
      skip_cleanup: true
      on:
        tags: true
    after_deploy:
    - rm -rf $TRAVIS_BUILD_DIR/app/samples/build/outputs

after_failure:
- cat $TRAVIS_BUILD_DIR/app/build/reports/lint-results.xml
