language: android
jdk: oraclejdk8
sudo: false

if: type == pull_request OR tag IS present

env:
  global:
  - API_LEVEL=28
  - EMULATOR_LEVEL=22
  - BUILD_TOOLS_VERSION=28.0.3
  - ABI=armeabi-v7a

android:
  components:
  - tools
  - platform-tools
  - build-tools-${BUILD_TOOLS_VERSION}
  - android-${API_LEVEL}
  - android-${EMULATOR_LEVEL} #todo
  - sys-img-${ABI}-android-${EMULATOR_LEVEL}

licenses:
- android-sdk-preview-license-.+
- android-sdk-license-.+
- google-gdk-license-.+

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  - $HOME/.android/build-cache

before_install:
- yes | sdkmanager "platforms;android-28"

stages:
- name: deploy #todo
- name: compile and test uikit
- name: compile and test modules
- name: compile and test samples
- name: ui tests

#  if: tag =~ ^\d+\.\d+\.\d+$

jobs:
  include:
  - stage: compile and test uikit
    name: common
    script: ./gradlew :uikit-common:check
  - stage: compile and test uikit
    name: common-sdk
    script: ./gradlew :uikit-common-sdk:check
  - stage: compile and test uikit
    name: compass
    script: ./gradlew :uikit-compass:check
  - stage: compile and test uikit
    name: compass-viewmodel
    script: ./gradlew :uikit-compass-viewmodel:check
  - stage: compile and test uikit
    name: poidetail
    script: ./gradlew :uikit-poidetail:check
  - stage: compile and test uikit
    name: positionlockfab
    script: ./gradlew :uikit-positionlockfab:check
  - stage: compile and test uikit
    name: positionlockfab-viewmodel
    script: ./gradlew :uikit-positionlockfab-viewmodel:check
  - stage: compile and test uikit
    name: zoomcontrols
    script: ./gradlew :uikit-zoomcontrols:check
  - stage: compile and test uikit
    name: zoomcontrols-viewmodel
    script: ./gradlew :uikit-zoomcontrols-viewmodel:check

  - stage: compile and test modules
    name: common
    script: ./gradlew :modules-common:check
  - stage: compile and test modules
    name: browsemap
    script: ./gradlew :modules-browsemap:check

  - stage: compile and test samples
    name: sample app
    script:
    - ./gradlew :app-samples:check

  - stage: ui tests
    name: browsemap
    before_script:
    - echo no | android create avd --force -n test -t android-${EMULATOR_LEVEL} --abi ${ABI}
    - emulator -avd test -no-audio -no-window &
    - android-wait-for-emulator
    - adb shell input keyevent 82 &
    script:
    - ./gradlew :app-samples-browsemap-default:connectedAndroidTest -P"sygic.sdk.key"=$SYGIC_API_KEY
    - ./gradlew :app-samples-browsemap-full:connectedAndroidTest -P"sygic.sdk.key"=$SYGIC_API_KEY
    - ./gradlew :app-samples-browsemap-modes:connectedAndroidTest -P"sygic.sdk.key"=$SYGIC_API_KEY
    - ./gradlew :app-samples-browsemap-markers:connectedAndroidTest -P"sygic.sdk.key"=$SYGIC_API_KEY
    - ./gradlew :app-samples-browsemap-details-window:connectedAndroidTest -P"sygic.sdk.key"=$SYGIC_API_KEY
    - ./gradlew :app-samples-browsemap-click-listener:connectedAndroidTest -P"sygic.sdk.key"=$SYGIC_API_KEY
    - ./gradlew :app-samples-browsemap-themes:connectedAndroidTest -P"sygic.sdk.key"=$SYGIC_API_KEY

  - stage: deploy
    name: assembleRelease
    before_script:
    - echo $RELEASE_KEYSTORE_BASE64 | base64 -d > $RELEASE_KEYSTORE_FILE
    script:
    - ./gradlew clean assembleRelease -P"sygic.sdk.key"=$SYGIC_API_KEY
#    todo: deploy to maven here - ./gradlew clean uploadArchives ?
    deploy:
      provider: releases
      api_key: $TRAVIS_RELEASE
      name: SygicMapsKit Android $TRAVIS_TAG
      file:
      - $TRAVIS_BUILD_DIR/app/samples/build/outputs/apk/release/*.apk
      - $TRAVIS_BUILD_DIR/modules/common/build/outputs/aar/*.aar
      - $TRAVIS_BUILD_DIR/modules/browsemap/build/outputs/aar/*.aar
      - $TRAVIS_BUILD_DIR/uikit/common/build/outputs/aar/*.aar
      - $TRAVIS_BUILD_DIR/uikit/common/sdk/build/outputs/aar/*.aar
      - $TRAVIS_BUILD_DIR/uikit/compass/build/outputs/aar/*.aar
      - $TRAVIS_BUILD_DIR/uikit/compass/viewmodel/build/outputs/aar/*.aar
      - $TRAVIS_BUILD_DIR/uikit/poidetail/build/outputs/aar/*.aar
      - $TRAVIS_BUILD_DIR/uikit/positionlockfab/build/outputs/aar/*.aar
      - $TRAVIS_BUILD_DIR/uikit/positionlockfab/viewmodel/build/outputs/aar/*.aar
      - $TRAVIS_BUILD_DIR/uikit/zoomcontrols/build/outputs/aar/*.aar
      - $TRAVIS_BUILD_DIR/uikit/zoomcontrols/viewmodel/build/outputs/aar/*.aar
      - $TRAVIS_BUILD_DIR/tools/injector/viewmodel/build/outputs/aar/*.aar
      skip_cleanup: true
      on:
        tags: true
