language: android
jdk: oraclejdk8
sudo: false

if: type == pull_request OR tag IS present

env:
  global:
  - ANDROID_API_LEVEL=28
  - ANDROID_BUILD_TOOLS_VERSION=28.0.3

android:
  components:
  - tools
  - platform-tools
  - android-$ANDROID_API_LEVEL
  - build-tools-$ANDROID_BUILD_TOOLS_VERSION

licenses:
- android-sdk-preview-license-.+
- android-sdk-license-.+
- google-gdk-license-.+

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  - $HOME/.android/build-cache

before_install:
- yes | sdkmanager "platforms;android-28"

stages:
- name: compile and test uikit
- name: compile and test modules
- name: compile and test samples
- name: ui tests
- name: deploy
  if: tag =~ ^\d+\.\d+\.\d+$

jobs:
  include:
  - stage: compile and test uikit
    name: common
    script: ./gradlew :uikit-common:check
  - stage: compile and test uikit
    name: common-sdk
    script: ./gradlew :uikit-common-sdk:check
  - stage: compile and test uikit
    name: compass
    script: ./gradlew :uikit-compass:check
  - stage: compile and test uikit
    name: compass-viewmodel
    script: ./gradlew :uikit-compass-viewmodel:check
  - stage: compile and test uikit
    name: poidetail
    script: ./gradlew :uikit-poidetail:check
  - stage: compile and test uikit
    name: positionlockfab
    script: ./gradlew :uikit-positionlockfab:check
  - stage: compile and test uikit
    name: positionlockfab-viewmodel
    script: ./gradlew :uikit-positionlockfab-viewmodel:check
  - stage: compile and test uikit
    name: zoomcontrols
    script: ./gradlew :uikit-zoomcontrols:check
  - stage: compile and test uikit
    name: zoomcontrols-viewmodel
    script: ./gradlew :uikit-zoomcontrols-viewmodel:check

  - stage: compile and test modules
    name: common
    script: ./gradlew :modules-common:check
  - stage: compile and test modules
    name: browsemap
    script: ./gradlew :modules-browsemap:check

  - stage: compile and test samples
    script:
    - ./gradlew :app-samples:check

  - stage: ui tests #todo: start emulator first?
    name: browsemap-default
    script: ./gradlew :app-samples-browsemap-default:connectedAndroidTest
  - stage: ui tests
    name: browsemap-full
    script: ./gradlew :app-samples-browsemap-full:connectedAndroidTest
  - stage: ui tests
    name: browsemap-modes
    script: ./gradlew :app-samples-browsemap-modes:connectedAndroidTest
  - stage: ui tests
    name: browsemap-markers
    script: ./gradlew :app-samples-browsemap-markers:connectedAndroidTest
  - stage: ui tests
    name: browsemap-details-window
    script: ./gradlew :app-samples-browsemap-details-window:connectedAndroidTest
  - stage: ui tests
    name: browsemap-click-listener
    script: ./gradlew :app-samples-browsemap-click-listener:connectedAndroidTest
  - stage: ui tests
    name: browsemap-themes
    script: ./gradlew :app-samples-browsemap-themes:connectedAndroidTest

  - stage: deploy
    script:
    - ./gradlew assembleRelease -P"sygic.sdk.key"=$SYGIC_API_KEY #todo credentials?
    deploy:
      provider: script #todo provider: releases
      script: echo 'deploing job done' #todo real deploy ;)
      file: $TRAVIS_BUILD_DIR/app/samples/build/outputs/apk/release/app-samples-arm64-v8a-release.apk
      skip_cleanup: true
    after_deploy:
    - rm -rf $TRAVIS_BUILD_DIR/app/samples/build/outputs
