version: 2.1

references:
  # Cache
  cache_key: &cache_key
    key: cache-{{ checksum "build.gradle" }}-{{ checksum "app/samples/build.gradle" }}-{{ checksum "modules/browsemap/build.gradle" }}-{{ checksum "modules/common/build.gradle" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "gradle.properties" }}
  restore_cache: &restore_cache
    restore_cache:
      <<: *cache_key
  save_cache: &save_cache
    save_cache:
      <<: *cache_key
      paths:
      - ~/.gradle

  # Docker
  android_config: &android_config
    working_directory: ~/sygic-maps-kit-android
    docker:
    - image: circleci/android:api-28 #todo: api-28-ndk ?
    environment:
      JVM_OPTS: -Xmx3200m

jobs:
  build: #todo build-test-and-deploy:
    <<: *android_config

    steps:
    - checkout
    - *restore_cache

    - run:
        name: Download Dependencies
        command: ./gradlew androidDependencies

    - run:
        name: Build UiKit Common
        command: ./gradlew :uikit-common:assembleDebug

    - run:
        name: Build UiKit Common SDK
        command: ./gradlew :uikit-common-sdk:assembleDebug

    #    - store_artifacts:
    #        path: app/samples/build/outputs/apk/
    #        destination: /apk/
    #    - store_artifacts:
    #        path: app/samples/build/reports/
    #        destination: /samples-app/

    - *save_cache

    - run:
        name: Run UiKit Common tests
        command: ./gradlew :uikit-common:check

    - run:
        name: Run UiKit Common SDK tests
        command: ./gradlew :uikit-common-sdk:check

#workflows:
#  build-test-and-deploy:
#    jobs:
#    - build
#    - unit_tests:
#        requires:
#        - build
#    - ui_tests:
#        requires:
#        - unit_tests