version: 2.1

jobs:
  build:
    working_directory: ~/sygic-maps-kit-android
    docker:
    - image: circleci/android:api-28 #todo: api-28-ndk ?
    environment:
      JVM_OPTS: -Xmx3200m

    steps:
    - checkout

    - restore_cache:
        keys:
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/samples/build.gradle" }}

    - run:
        name: Download Dependencies
        command: ./gradlew androidDependencies

    - save_cache:
        paths:
        - ~/.gradle
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/samples/build.gradle" }}

    - run:
        name: Run Tests
        command: ./gradlew check