name: Build, Test and Deploy

on: [push]

jobs:
  All:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1.0.0
    - name: Set-up workspace
      uses: actions/setup-java@v1.0.0
      with:
        java-version: 1.8
    - name: Build
      run: ./gradlew :app-samples:check
    - name: Ui Tests
      uses: msfjarvis/setup-android@0.1
#      run: ./test.sh