name: Build, Test and Deploy

on: [push]

jobs:
  All:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Set-up workspace
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build
      run: ./gradlew :app-samples:check
    - name: Ui Tests
      uses: vgaidarji/android-github-actions/emulator@v1.0.0