name: Build, Test and Deploy

on: [push]

jobs:
  All:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1.0.0
    - name: Set-up workspace
      uses: msfjarvis/setup-android@0.1
    - name: Build
      run: ./gradlew :app-samples:check
#    - name: Ui Tests
#      run: ./test.sh